site_name: Snipe Scripts
site_url: https://pushkart2.github.io/gitbook/
repo_url: https://github.com/pushkart2/gitbook
repo_name: pushkart2/gitbook
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/AeCVP2F8h7
    - icon: fontawesome/brands/github
      link: https://github.com/pushkart2

nav:
  - Home: index.md
  - Restaurants: restaurants.md
  - Crafting: crafting.md
  - DonatorSystem: donatorsystem.md
  - Evidence System: evidence.md
  - Motel: motel.md
  - Admin Menu: adminmenu.md
  - Banking: banking.md
  - Beekeeping: beekeeping.md
  - Blips: blips.md
  - Furniture Stash: furniturestash.md
  - Icebox: icebox.md
  - Invoices: invoices.md
  - Meth: meth.md
  - Moonshine: moonshine.md
  - Multi Job: multijob.md
  - Owned Shops: ownedshops.md
  - PoliceCams: policecams.md
  - Printer: printer.md
  - Wigs: wigs.md
  - Winery: winery.md
